// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOY6EIp1239CgicNbTccl77QGbS-bxn1w',
    appId: '1:521780371207:web:3f5dd74a633ff8c5cdafa2',
    messagingSenderId: '521780371207',
    projectId: 'nvldapp',
    authDomain: 'nvldapp.firebaseapp.com',
    storageBucket: 'nvldapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwmuCHVXMkV5-RM-DqGH5793qKsZlpNE',
    appId: '1:521780371207:android:5d052c68affc9858cdafa2',
    messagingSenderId: '521780371207',
    projectId: 'nvldapp',
    storageBucket: 'nvldapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTi-3IOB0z3rK7-D8Q4o3M31JMd6gqU1Y',
    appId: '1:521780371207:ios:29c56be1af5325b4cdafa2',
    messagingSenderId: '521780371207',
    projectId: 'nvldapp',
    storageBucket: 'nvldapp.appspot.com',
    androidClientId: '521780371207-2e8k8fh7ubj4pm016e2qlte7rtomigcq.apps.googleusercontent.com',
    iosClientId: '521780371207-7oppeo5kckknv9apn7vp1p2ldn2brjbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nvldApp',
  );
}
